# Generated by Django 2.1.5 on 2019-05-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('autor', models.CharField(blank=True, max_length=70, null=True, verbose_name='Autor')),
                ('editora', models.CharField(blank=True, max_length=70, null=True, verbose_name='Editora')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('ano', models.IntegerField(blank=True,null=True,verbose_name='Ano')),
                ('autor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do autor')),
            ],
        ),
    ]