# Generated by Django 2.1.5 on 2019-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_dependente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='tel_celular',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='tel_fixo',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
